language: node_js
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: GMnGHau4TB4wztSflPEVZz+o2g1bwhs7h/RUpS/tXpMDP9KqTKwrT7H+g8de34y5YmT/m/hbNylIDGjomFQUeIs0wIhv1arQlQw+VsWwLEX7pBRq2Wy8ADgZICxntZPGFKGiuykwXonMTQopoNAm53SoRUp9ldNAz++kuevubaw=
  app: collidingobjects-staging
  on:
    repo: imaman/green-site
