#!/usr/bin/env node
var argv = require('minimist')(process.argv.slice(2));
var promoter = require('./acceptance/promoter.js');

promoter('collidingobjects-staging', 'collidingobjects', argv.status);


