#!/usr/bin/env node
var argv = require('minimist')(process.argv.slice(2));
var promoter = require('./acceptance/promoter.js');

function bail(err) {
  if (!err) {
    process.exit(0);
  }

  if (err.stack) {
    console.log(err.stack);
    process.exit(1);
  }

  console.log('**************************************************');
  console.log('*                                                *');
  console.log('* PROMOTION HALTED                               *');
  console.log('*                                                *');
  console.log('* Reason: ' + err);
  console.log('*                                                *');
  console.log('**************************************************');
  process.exit(1);
}


  
promoter('collidingobjects-staging', 'collidingobjects', { status: argv.status }, bail);


