#!/usr/bin/env node
var argv = require('minimist')(process.argv.slice(2));
var promoter = require('./acceptance/promoter.js');
var JasmineNodeApi = require('./acceptance/jasmine-node-api');
var acceptanceSpecs = require('./acceptance/specs.js');

function bail(err, text) {
  if (!err) {
    return console.log(text);
  }

  if (err.stack) {
    console.log(err.stack);
    process.exit(1);
  }

  console.log('**************************************************');
  console.log('*                                                *');
  console.log('* PROMOTION HALTED                               *');
  console.log('*                                                *');
  console.log('* Reason: ' + err);
  console.log('*                                                *');
  console.log('**************************************************');
  process.exit(1);
}

var options = { 
  status: argv.status, 
  runSpecs: function(done) { new JasmineNodeApi().runSpecs(acceptanceSpecs, done) }
};

promoter('collidingobjects-staging', 'collidingobjects', options, bail);


